honeycombio/honeycomb-opentelemetry-java

- README.md
Also updates OTel SDK versions to 1.1.0
> Add instructions for adding OTEL sdks using maven in README

- CHANGELOG.md
- DEVELOPMENT.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
> Prep for v0.1.1

- README.md
- sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
- sdk/src/test/java/io/honeycomb/opentelemetry/HoneycombSdkTest.java
> Add SDK builder method for passing in BaggageSpanProcessor or any custom SpanProcessor

- DEVELOPMENT.md
- agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
* consolidate constants
* allow local publishing without secrets
* Closes #16
> DRY up constants between modules

- sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
* Formatter decided javadocs needed updating -- I don't want to fiddle with settings, this is what it's doing by default. If this becomes an issue, we should add an editorconfig
* Closes #59
> Add baggage propagator to the SDK

- CHANGELOG.md
- DEVELOPMENT.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- docs/README.md
Prepares the v0.3.0 release by using version numbers, add to change log and all references to use latest version.
> Prepare v0.3.0 release

- README.md
- agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
* downgrade missing apiKey/dataset to a warning
* closes #83
> Make API Key and Dataset optional

- .github/workflows/stale.yml
- Only applies stale to info needed or revision needed
> Only apply stale to info needed or revision needed

- README.md
- RELEASING.md
> docs: add OTEL version to readme

- .circleci/config.yml
- gradle/wrapper/gradle-wrapper.properties
- Java 17 warm off the press as the new LTS version: https://en.wikipedia.org/wiki/Java_version_history
- had to bump gradle version as well
> ci: add Java 17 to test matrix

- README.md
- agent/build.gradle
- build.gradle
Updates the OpenTelemetry SDK and Agent dependencies to latest. Also includes updating the agent path after it was amended.
- Closes #150 
- update sdk to 1.7.1
- update agent to 1.7.2 (includes removing agent `-all` suffix)
- updates README with version details
> Update OpenTelemetry SDK and Agent

- CHANGELOG.md
- DEVELOPMENT.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- prepare v0.7.0 release
- update project version to 0.7.0
- update changelog
> prepare v0.7.0 release

- examples/spring-agent-manual/build.gradle
- examples/spring-agent-only/build.gradle
- sdk/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java
- parent-based sampler would not work because we need to know what SampleRate to set
- closes #234 
-
> remove parent-based sampler

- CHANGELOG.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- Version bump and update changelog for release.
- Noted new upstream OTel in README!
> Prepare v0.8.0

- CHANGELOG.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
> prepare 0.8.1 release

- README.md
- I want a pretty thing that tells me latest artifact version in Maven 💟 
- Using the agent artifact as the canonical thing, versions are the same across artifacts.
> docs: add maven badge

- CHANGELOG.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Prepares the v0.10.0 release.
- Adds change log entry
- Updates library version to 0.10.0 in build.gradle and distro metadata attributes
> Prepare v0.10.0 release

- build.gradle
- bump to latest available otel version prior to 1.0 release
- closes #271 
-
> bump otel version from 1.11 to 1.12.0

- CHANGELOG.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- prep for 1.0 release tomorrow (Mar 23) 🎊
- closes #272 
- taking the BETA note out of readme
- keeping the OSS lifecycle as `active` for now
> prepare 1.0.0 release

- CHANGELOG.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
> Prepare 1.1.0 release

- CHANGELOG.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- prep release patch v1.1.1
- update version and snapshot in main `build.gradle`
- update version in `DistroMetadata.java`
- update changelog
> prep release patch v1.1.1

- CHANGELOG.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- Prepare release v1.2.0
- update project version to 1.2.0, 1.2.1-SNAPSHOT
- Update version in DistroMetadata (same proto)
- Update README with new otel versions
- update CHANGELOG
> Prep release v1.2.0

- CHANGELOG.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Prepares the v1.3.0 release.
- Docs https://github.com/honeycombio/docs/pull/1342
- Poodle onboarding https://github.com/honeycombio/hound/pull/10560
- Updates versions to 1.30
- Adds changelog entry
> Prepare v1.3.0 release

- CHANGELOG.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
> prepare 1.4.0 release

- .github/dependabot.yml
> chore: Dependabot fixes

- CHANGELOG.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
> rel: prepare release 1.4.2

- licenses/licenses.md
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/byte-buddy-dep-1.14.4.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/byte-buddy-dep-1.14.4.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/jackson-core-2.14.2.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/jackson-core-2.14.2.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/jackson-jr-objects-2.14.2.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/jackson-jr-objects-2.14.2.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/okhttp-4.10.0.jar/okhttp3/internal/publicsuffix/NOTICE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/slf4j-api-2.0.7.jar/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/slf4j-simple-2.0.7.jar/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/zipkin-2.23.2.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/zipkin-reporter-2.16.3.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.25.0.jar/META-INF/licenses/zipkin-sender-okhttp3-2.16.3.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.25.0.jar/inst/META-INF/LICENSE.renamed
- licenses/opentelemetry-javaagent-1.25.0.jar/inst/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.25.0.jar/inst/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.25.0.jar/inst/okhttp3/internal/publicsuffix/NOTICE
> maint: update licenses in prep for release

- CHANGELOG.md
- README.md
- RELEASING.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- new release v1.5.0
- update changelog for new release
- update readme with new otel v1.23.0
- update distro version to 1.5.0
- update release note for docs
- licenses updated in #419
> rel: prep v1.5.0

- licenses/licenses.md
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/byte-buddy-dep-1.14.5.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/byte-buddy-dep-1.14.5.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/jackson-core-2.15.2.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/jackson-core-2.15.2.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/jackson-jr-objects-2.15.2.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/jackson-jr-objects-2.15.2.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/okhttp-4.11.0.jar/okhttp3/internal/publicsuffix/NOTICE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/slf4j-api-2.0.7.jar/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/slf4j-simple-2.0.7.jar/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/zipkin-2.23.2.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/zipkin-reporter-2.16.3.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.27.0.jar/META-INF/licenses/zipkin-sender-okhttp3-2.16.3.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.27.0.jar/inst/META-INF/LICENSE.renamed
- licenses/opentelemetry-javaagent-1.27.0.jar/inst/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.27.0.jar/inst/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.27.0.jar/inst/okhttp3/internal/publicsuffix/NOTICE
- new licenses needed
- Ran `./gradlew generateLicenseReport` to update project dependency licenses
> maint: update licenses for new otel-java versions

- licenses/licenses.md
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/byte-buddy-dep-1.14.12.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/byte-buddy-dep-1.14.12.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-annotations-2.17.0.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-annotations-2.17.0.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-core-2.17.0.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-core-2.17.0.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-databind-2.17.0.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-databind-2.17.0.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-dataformat-yaml-2.17.0.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/jackson-dataformat-yaml-2.17.0.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/okhttp-4.12.0.jar/okhttp3/internal/publicsuffix/NOTICE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/slf4j-api-2.0.12.jar/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/slf4j-simple-2.0.12.jar/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/zipkin-2.27.1.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/zipkin-reporter-3.3.0.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.33.1.jar/META-INF/licenses/zipkin-sender-okhttp3-3.3.0.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.33.1.jar/inst/META-INF/LICENSE.renamed
- licenses/opentelemetry-javaagent-1.33.1.jar/inst/META-INF/LICENSE.txt
- licenses/opentelemetry-javaagent-1.33.1.jar/inst/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.33.1.jar/inst/okhttp3/internal/publicsuffix/NOTICE
- updated licenses for upcoming release 
- Ran `./gradlew generateLicenseReport` to get updated licenses for upcoming release
> maint: update licenses for upcoming release

- CHANGELOG.md
- README.md
- RELEASING.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
- Prepares v1.7.0 release
- Update version to 1.7.0
- Update changelog
- Update release notes
> rel: prepare v1.7.0 release
