honeycombio/honeycomb-opentelemetry-java

- README.md
- agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
- custom/src/main/java/io/honeycomb/opentelemetry/DistroMetadataResourceProvider.java
- custom/src/main/java/io/honeycomb/opentelemetry/HoneycombSdkTracerProviderConfigurer.java
- custom/src/main/java/io/honeycomb/opentelemetry/ServiceNameResourceProvider.java
- custom/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider
Fixes #40
Previously, we were clobbering any resource attributes set via environment variable (`OTEL_RESOURCE_ATTRIBUTES`) or properties (`otel.resource.attributes`). This change uses the OTel Java autoconfiguration SPI to set the service name and distro metadata fields via a ResourceProvider ([example](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/0c7a20d3fdcfcfa605fe997d669dd3608c79408f/examples/distro/custom/src/main/java/com/example/javaagent/DemoResourceProvider.java)). This is akin to the pattern for configuring the trace provider via an `SdkTracerProviderConfigurer` that we're already using to customize tracing.
We're keeping the clobber of `otel.exporter.otlp.(headers|endpoint)` properties in `HoneycombAgent.configure()` because those properties …
> set service name and distro metadata via SPI

- .circleci/config.yml
- RELEASING.md
- agent/build.gradle
- build.gradle
- common/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- sdk/build.gradle
- sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
Fixes #20 
got inspiration here: https://github.com/honeycombio/opentelemetry-java-exporter/blob/main/exporters/build.gradle and a myriad other places 🔮 
we have multi-module setup, so in order not to copy-pasta all the publishing setup, I put it in a conditional block in the parent gradle file
* adds publish step to CI
* copy all built jars to GitHub, not just the agent jar
* fix javadoc errors
Tested publishing to local Maven. Also tested publishing to snapshot repo in sonatype, and pulled that down in a local test app. Tested CI publish step as far as uploading the release to "staging" in sonatype.
The real test will be tagging a release when we're ready. This is still not fully automated yet, we will need to manually push the "release" button in sonatype. I figured we can automate …
> Add maven publish

- docs/README.md
- sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
Fixes #37. Creating methods for adding arbitrary resource attributes to the builder. We already use resource attributes to store the service name, so this just adds an AttributeBuilder to the Sdk builder which collects a list of attributes that the user can add to.
```java
HoneycombSdk honeycomb = new HoneycombSdk.Builder()
.setApiKey(YOUR_API_KEY)
.setDataset(YOUR_DATASET)
.setServiceName(YOUR_SERVICE_NAME)
.addResourceAttribute("java.version", System.getProperty("java.version")) // optional
.build();
```
This will result in a resource with attributes "`service.name`" and "`java.version`".
> Create methods for adding arbitrary resource attributes

- .github/dependabot.yml
- sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
* allow setting additional span processors in SDK
* fix: dependabot was configured for maven instead of gradle
* Fixes #51
> Fix: use additional span processors in SDK builder

- RELEASING.md
- agent/build.gradle
- build.gradle
- common/build.gradle
- sdk/build.gradle
* add description to POMs
* add note about testing staged artifacts
* Fixes #64 
Tested locally: publish to Sonatype, close (validation passed), use in test app.
> Fix Sontaype pom validator

- sdk/build.gradle
So users only need to depend on the Honey SDK when enriching their code with spans and attributes
> Add opentelemetry-extension-annotations as api dependency in the sdk

- sdk/src/test/java/io/honeycomb/opentelemetry/DeterministicTraceSamplerTest.java
Adds deterministic sampler tests including set of trace IDs used to ensure compatibility with other Honeycomb implementations.
> Add deterministic sampler tests

- agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
Fixes #90 .
Metrics are not yet configured in the Honeycomb OTEL Java Distribution. This disables metrics by default until configuration is added.
> Disable metrics by default

- .github/workflows/stale.yml
- Adds Stalebot effective Sept 1 2021
For any new issues or PRs created starting September 1, 2021, this will run once daily.
- Issues with no activity will be marked stale after 14 days
- PRs with no activity will be marked stale after 30 days
- Stale issues with no activity will be closed after 7 days
- Stale PRs with no activity will be closed after 7 days
> Add Stalebot effective Sept 1 2021

- .github/workflows/stale.yml
- Update Stalebot to actually be Sept 1, not January 9. Copy pasta of incorrect example for date format.
> Update start-date on stalebot to be Sept 1

- README.md
- build.gradle
Updates the OpenTelemetry SDK and agent to newer versions. While v1.6.0 of the SDK is available, I updated to v1.5.0 because that matches the latest agent and it's good to keep them in step.
- update OpenTelemetry SDK and agent dependencies to 1.5.0/1.5.3 respectively
> Update OpenTelemetry SDK to 1.5.0 and agent to 1.5.3

- agent/src/main/java/io/honeycomb/opentelemetry/HoneycombAgent.java
- common/build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
OTel metrics were disabled in the HoneycombAgent wrapper (#92) because metrics should be sent to different datasets than trace data. However there was only one way to specify the a dataset so both trace and metrics data was being sent to the same dataset.
This change adds support for enabling metrics in agent mode by setting a metrics dataset, and optionally set a different endpoint and API key by providing some new system properties or environment variables
- Closes #96 
- add options for setting trace and metrics endpoint, API key and dataset vis system properties and env vars
- new system properties and env vars will fall back to the original system properties / env vars so they are backward compatible
- If a MetricsDataset is set, we enable the metrics OTLP exporter via setting [OTLP …
> Add support for enabling OTel metrics

- .circleci/config.yml
- build.gradle
- publishing to maven still requires manually closing/releasing the artifacts after CI does the "publish" task
- use the nexus-publish plugin to automate the rest of the process
- verified from my machine that publish and close works (didn't want to actually release anything)
- will update releasing.md next time we do a release and confirm that everything works as expected
- fixes #66
> automate nexus publish/close/release

- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
The `telemtry.sdk.{name, language, version}` resource attributes are missing when creating traces using the manually configured OpenTelemetry SDK using the OpenTelemetryConfiguration.builder. We should include the base OpenTelemetry SDKs attributes so both we and the user applications can see that information.
- Closes #116 
- Updates the manual builder to merge the default Resource with the one we create with our own `distro` attributes.
Before and after:
> Ensure SDK configurator applies core SDK resource attributes

- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
`:sdk:javadoc` was warning about a missing param doc
> add javadoc for method param

- build.gradle
- custom/src/main/java/io/honeycomb/opentelemetry/DistroMetadataResourceProvider.java
- custom/src/main/java/io/honeycomb/opentelemetry/HoneycombSdkTracerProviderConfigurer.java
- custom/src/main/java/io/honeycomb/opentelemetry/ServiceNameResourceProvider.java
branching from dependabot to get an extra set of eyes, see [update to the example distro](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4120/files)
- Closes #140
> Bump otel to 1.6.0

- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- otel 1.6.0 defaults otel.metrics.exporter to "none"
- metrics export broke after upgrading to otel 1.6.0 
- enable the `otel.metrics.exporter` when honeycomb metrics dataset is configured
- no longer necessary to explicitly disable metrics otherwise
> fix: metrics export

- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- sdk/build.gradle
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
We currently try to capture the process runtime using a custom attribute when configured to run with the OTel SDK. This PR removes the custom attributes and uses built-in OTel resources that capture OS and runtime attributes.
- Remove custom attributes from DistroMetadata for language and runtime
- Import OTel SDK resource extensions package
- Merge OsResource and RuntimeResource when building the Resource to use for the SDK
NOTE: These are the same resources that are automatically configured and used when running with the agent.
> Use built-in OTel resources for OS & runtime

- RELEASING.md
- verified with latest release that the new gradle plugin published, closed, and released the new version to Maven
-
> docs: sonatype release is automated

- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Re-adds the java runtime distro metadata field that was removed in a previous PR.
- Resolves #157 
- Re-add the `honeycomb.distro.runtime` field with the value that is the same as the [OTEL SDK](https://github.com/open-telemetry/opentelemetry-java/blob/df1f47d9298efa755a4bff358e2c34b0f1de7770/sdk-extensions/resources/src/main/java/io/opentelemetry/sdk/extension/resources/ProcessRuntimeResource.java#L30)
> re-add java runtime version distro metadata

- common/build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- Closes #158 
- In [v0.5.0](https://github.com/honeycombio/honeycomb-opentelemetry-java/releases/tag/v0.5.0) we enabled support for metrics, and introduced a new dependency on `com.google.guava:guava:30.1.1-jre` to detect the existence of a metrics dataset. Somehow this library prevents the agent from working on its own without manually adding a dependency on gRPC (either via direct dependency or transitive through sdk).
- This PR removes that dependency, but still checks whether the metrics dataset variable is null.
To confirm it works, remove the `:sdk` dependency and manual instrumenting from the spring-agent example app, and `../../gradlew bootRun` from sprint-agent directory. Curling the endpoint should produce telemetry in honeycomb (enable `OTEL_JAVAAGENT_DEBUG` to see in console …
> fix: Remove google guava dep that suppressed gRPC

- examples/spring-agent/src/main/java/io/honeycomb/examples/springbootagent/Application.java
- examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/Application.java
- Simplify output on example apps to match that of Spring Agent
- Remove bean names, replace with "OK I'm ready now!"
> Simplify output in example apps

- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
- sdk/src/test/java/io/honeycomb/opentelemetry/OpenTelemetryConfigurationTest.java
When using `OpenTelemetryConfiguration.Builder` to add resource attributes, the `AttributesBuilder` is returned instead of the `Builder`. This means it is not possible to chain multiple calls to the top-level builder.
- Fixes #191 
- update each of the `addResourceAttribute` overloads to return the top-level `Builder` instead of the `AttributesBuilder`
- add basic test to ensure the API can be used in the expected way
NOTE: The test does not actually verify that attributes are added to the resource as the `Resource` object is not available to retrieve from the `TracerProvider`. It may be possible to use reflection to do it later.
> Return OpenTelemetryConfiguration.Builder when adding resource attributes

- Makefile
- build.gradle
A general sadness around non-Java tooling not knowing what the current project version is.
This is a gradle task and a make target for looking up what the canonical version of the project is at the time. Something useful that shook out of [the Too Much Make experiment](https://github.com/honeycombio/honeycomb-opentelemetry-java/pull/195).
> teach gradle/make to display the project version

- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
Adds support for providing configuration via a properties file. Also sets the otel system variable to the same path if one has not been set.
- Closes #14
NOTE: There are not tests for this yet, it probably makes sense to use a smoke test as this is related to setting system properties & env vars
- Updates EnvironmentConfiguration to look for `honeycomb.config.file` system property then `HONEYCOMB_CONFIG_FILE` environment variable as properties file path
- If a path is found, loads the file into an instance of `Properties`
- Update `readVariable` to check the properties file, then system properties and then environment variables
- Sets `otel.javaagent.configuration-file` system property, if it's not already set, so OTel java agent will try to read from the same file
> Add support for properties files

- examples/spring-agent-manual/src/main/java/io/honeycomb/examples/springbootagentmanual/HelloController.java
- smoke-tests/smoke-agent-manual.bats
Adds a smoke test for the BaggageSpanProcessor to verify new spans have the expected attributes.
- Closes #190 
- Depends on #197
- Updates spring-agent-manual example app to set a baggage attribute
- Add spring-agent-manual smoke test to verify the attribute is added to new span
PS @robbkidd dis all of this work, I just copy/pasted into new commit 😄
> Add smoke test for baggage span processor

- smoke-tests/docker-compose.yml
- smoke-tests/smoke-agent-only.bats
- smoke-tests/test_helpers/utilities.bash
- #168 
- Metrics dataset added to all tests (though smoke only in agent-only scenario)
- Smoke test added to `smoke-agent-only` to check for existence of metrics
- More simplifying / breaking up of utility functions
- Each smoke test for a single example app uses a single instance of collector (instead of tearing down between tests)... but collector tears down between each example app smoke test
- Metrics have a shorter time interval specified to get results faster, and wait longer before checking for data
> Add Smoke test for JVM metric being emitted

- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
- sdk/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java
- sdk/src/test/java/io/honeycomb/opentelemetry/DeterministicTraceSamplerTest.java
Updates the DeterministicSampler to internally create and use a ParentBased sampler that uses a TraceIdRatioBased Sampler as it's root. The combination of ParentBased and RatioBased samplers ensure that root span's mark the trace as sampled / not sampled based on a 1/X sample rate, then subsequent spans within the same trace use the same sampling decision.
This PR reduces the complexity of our implementation and depends on the core samplers to better support multi-service & beeline / OTel environments.
- Resolves #196
- Replace custom logic in DeterministicSampler with internally created Otel core ParentBasedSampler and TraceIdRatioBased sampler
- Sets the DeterministicSampler with a sample rate of 1 (always sampler) as the default sampler when configuring the OpenTelemetry SDK
- Update …
> Update DeterminisitcSampler to use OTel core Parent/TraceIDRatio samplers

- Makefile
- agent/build.gradle
- custom/build.gradle
- examples/spring-agent-manual/build.gradle
- examples/spring-agent-only/build.gradle
- Closes #213 
- Since upstream OTel no longer has the `-all` suffix, remove from our artifacts where applicable. The builds creating shadow jars needed changes per [Configuring Shadow](https://imperceptiblethoughts.com/shadow/configuration/#configuring-output-name)
- Examples also dropped `-all` and the Makefile no longer looks in `-all` for smoking.
[CI Step showing old build includes `-all` jars](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-java/807/workflows/2130c44a-eed2-471d-be61-147d0fd5a68d/jobs/3038/parallel-runs/0/steps/0-107)
[CI Step showing new build has no `-all` jars](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-java/814/workflows/ab4c69b1-6bbf-4ceb-a9d9-3a03caf14d40/jobs/3073/parallel-runs/0/steps/0-107)
> Remove -all suffix from artifacts

- .circleci/config.yml
- [publish_maven step in ci](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-java/821/workflows/82b49453-d6d8-4b00-8d06-311a55621329/jobs/3110/parallel-runs/0/steps/0-106) failed in [tagged release](https://github.com/honeycombio/honeycomb-opentelemetry-java/runs/4316109374)
- When working on smoke-tests in #197 , everything got moved from /build/libs directory to a single /build-artifacts directory. This was missed in the publish_maven step of the Circle CI config so it was trying to copy from a directory that didn't exist.
> publish_maven needs updated directory of jars

- .circleci/config.yml
- .gitignore
- smoke-tests/smoke-agent-manual.bats
- smoke-tests/smoke-agent-only.bats
- smoke-tests/smoke-sdk.bats
- smoke-tests/test_helpers/utilities.bash
- we still have some flaky smoke tests
- when a test fails for a legitimate reason, it's hard to tell *why* without seeing the data.json
- updates #233 
- preserve data.json from each test in a circle artifact for later investigation
- make root `jq` lookup more resilient: the data file contains both `resourceSpans` and `resourceMetrics` on different lines, adding a `?` makes it not bark about nulls on unmatched lines
> update smoke tests

- sdk/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java
Object creation optimization
Small optimization to extract the creation of the `AttributeKey` for the SampleRate into a private static final to avoid creation for each span processed.
> Create the AttributeKey for SampleRate once

- README.md
- build.gradle
Bump the version of the java-instrumentation library to 1.9.2 to address a memory and connection leak for reactor-netty
https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.9.2
> Bump opentelemetryJavaagent to 1.9.2 to address memory leak in reactor-netty

- .circleci/config.yml
- Makefile
- RELEASING.md
- build.gradle
- we want to exercise our publish pipeline more regularly than just at release time
- having snapshots in maven makes it easier to test artifacts without the need to build them locally
- closes #247 
- release to maven on every commit to `main`!
- the publish plugin will push things to the snapshot repo if the project version ends in `SNAPSHOT`, and to the main repo otherwise
- publish job was not storing artifacts in CI -- fixed
- this adds another manual step of updating the snapshot version when updating the release version
- this is the first step in getting dev releases started, I think we can iterate in the future:
- consolidate version number in a single place (right now it's twice in build.gradle and in DistroMetadata)
- maybe use the circle tag as the source of truth for what's …
> Publish snapshots

- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
- closes #256 
- Details are captured in the issue. In E&S, dataset is no longer required but service name is. Warnings have been added to help guide changes that may be needed for missing properties.
- Note: no changes to metrics
Logging output when missing all variables:
```shell
WARN: Missing service name. Specify either SERVICE_NAME environment variable or service.name system property. If left unset, this will show up in Honeycomb as unknown_service:java
WARN: Missing API key. Specify either HONEYCOMB_API_KEY environment variable or honeycomb.api.key system property.
```
Logging output, using all variables (non-legacy key, service name set to jamie_service):
```shell
WARN: Dataset is ignored in favor of service name. Data will be sent to service name: jamie_service
```
Logging output …
> feat: provide more feedback to users to help configure for use in E&S

- CHANGELOG.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- The lack of a v0.9.0 release in the world.
- Updated versions and changelog.
> Prepare v0.9.0

- custom/src/main/java/io/honeycomb/opentelemetry/HoneycombAutoConfigurationCustomizerProvider.java
- custom/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider
- custom/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.SdkTracerProviderConfigurer
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
- Update use of upstream OTel Java interfaces that are deprecated and will disappear at some point in the future.
- get a LoggingSpanExporter via create()
> The constructor LoggingSpanExporter() is deprecated.
> io.opentelemetry.exporter.logging.LoggingSpanExporter.LoggingSpanExporter()
> Deprecated Use create().
OK.
- change our autoconfig via SPI over to the new way
> io.opentelemetry.sdk.autoconfigure.spi.traces.SdkTracerProviderConfigurer
> Deprecated Use AutoConfigurationCustomizer.addTracerProviderCustomizer(BiFunction).
This dep notice was not super clear on remediation advice. The changes in this PR are based on [the update](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5574/files) to the otel-java-instrumentation's own demo distribution to address the …
> resolve deprecations from upstream

- Makefile
- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
- sdk/build.gradle
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
- sdk/src/test/java/io/honeycomb/opentelemetry/OpenTelemetryConfigurationTest.java
- smoke-tests/docker-compose.yml
- smoke-tests/smoke-sdk-grpc.bats
- smoke-tests/smoke-sdk-http.bats
- smoke-tests/smoke-sdk.bats
Add support for the SDK to read the OTEL system property or environment variable used to determine the protocol to send trace spans with the OTLP Span Exporter.
You can set the protocol either in one of the following ways:
- System property: `-Dotel.exporter.otlp.protocol=grpc|http/protobuf`
- Environment variable: `export OTEL_EXPOTER_OTLP_PROTOCOL=grpc|http/protobuf`
- `OpenTelemetryConfiguration.builder().setOtlpProtocol("grpc|http/protobuf")`
- Closes #282 
- Add static properties to EnvironmentConfigurion to OTLP grpc and HTTP protocols
- Add getOtlpProtocol to EnvironmentConfiguration
- Add unit test to verify grpc is default exporter and can swap in HTTP exporter
- Splits sdk-only smoke tests to execute both for grpc and http exporters
- includes reworking docker compose file and …
> Adds support for SDK to set OTLP protocol

- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- Closes #295 
- Fixed false warning about SERVICE_NAME not being defined when OTEL_SERVICE_NAME was defined. 
- Defined OTEL_SERVICE_NAME private environment variable.
- Created getOTelServiceName private function
- Changed warning logic for missing service name to accept either version.
> Fixed false warning  when OTEL_SERVICE_NAME was present.

- RELEASING.md
- common/build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
Adds the `x-otlp-version` header that indicates what version of OTLP the distro is using. This is useful for understanding what proto versions users are sending to us.
- Implements https://github.com/honeycombio/specs/pull/5
- Add `org.apache.commons` compile dependency to common package
- Extends DistroMetadata to track the `x-otlp-version` header with current value (0.16.0)
- Add EnvironmentConfiguration.getHeaders which creates a `Map<String, String>` that contains the honeycomb and new otlp proto version headers
- Update EnvironmenyConfiguration enableOTLPTraces and enableOTLPMetrics to use new header map
- Update sdk OpenTelemetryConfigurator to use new header map when setting up the builder
> Add OTLP version to headers (HTTP & gRPC)

- RELEASING.md
- we now also include the distro version in our onboarding quickstart UI - this wasn't listed previously
- sometimes it's easy to miss the docs PR step because it's at the end of the releasing guide
- Move docs PR steps to the top to reduce chance of forgetting as part of the releasing process
- Add specific places for updates in public docs
- Add onboard PR step
> docs: include onboard docs in releasing, move to top

- common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java
- common/src/test/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSamplerTest.java
- custom/src/main/java/io/honeycomb/opentelemetry/HoneycombAutoConfigurationCustomizerProvider.java
Fixes #315: Agent Auto Configuration can overwrite an extension's customer Sampler
Changes the way the Honeycomb agent configures the tracer by decorating the existing Sampler rather than replacing it. Also changes the implementation of DeterministicTraceSampler to function as a decorating/filtering Sampler rather than 100% authoritative.
> Decorate existing Sampler with DeterministicTraceSampler instead of replacing it

- .gitignore
- build.gradle
- Something to inform automation about release data like versions and possibly shasums and the like in the future.
- For the short term, intended to help updating the documentation site with latest version info.
- Include it in release artifacts!
```
» ./gradlew build
BUILD SUCCESSFUL in 4s
57 actionable tasks: 5 executed, 52 up-to-date
» cat build-artifacts/release.json 
{
"repo_name": "honeycombio/honeycomb-opentelemetry-java",
"version": "1.2.1-SNAPSHOT"
}
```
> produce a JSON of release info on build

- .circleci/config.yml
- closes #317 
- copy the versioned agent and rename without the version
- the glob pattern specifies any file in the directory that starts with honeycomb-opentelemetry-javaagent and does not include any letters afterward before ending in `.jar`. The goal is to get only the main agent jar (e.g. `honeycomb-opentelemetry-javaagent-1.2.3.jar`) and exclude `honeycomb-opentelemetry-javaagent-1.2.3-sources.jar`, `-javadoc.jar`,  etc.
selected results from local circle testing:
```
-rw-r--r-- 1 circleci circleci 14330009 Jul  5 22:22 honeycomb-opentelemetry-javaagent-1.2.42.jar
-rw-r--r-- 1 circleci circleci    18699 Jul  5 22:22 honeycomb-opentelemetry-javaagent-1.2.42-javadoc.jar
-rw-r--r-- 1 circleci circleci     1090 Jul  5 22:22 honeycomb-opentelemetry-javaagent-1.2.42-sources.jar
```
after …
> maint: add un-versioned copy of agent to Github assets

- .circleci/config.yml
Follow up to honeycombio/honeycomb-opentelemetry-java#319
release.yaml doesn't get published to Maven, but is persisted in `./publish-artifacts` so that it is included in the artifacts stored for this job and in the artifacts included in the `publish_github` job.
> maint: include generated release.yml in published artifacts

- .circleci/config.yml
- Java 18 was released in March 😄 
- add to test matrix
- bump to latest gradle orb while we're at it
> maint: add Java 18 to CI matrix

- .circleci/config.yml
- https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-java/1370/workflows/a4ce7ef3-4333-4cc1-af5c-1aeecdd140d7/jobs/5884
- build-artifacts contains release.JSON not YAML
- just copy all the things from build-artifacts to publish-artifacts :shrug:
> maint: fix build

- .circleci/config.yml
- common/src/test/java/io/honeycomb/opentelemetry/sdk/trace/spanprocessors/BaggageSpanProcessorTest.java
- we miss failing CI builds on main
- send a slack notification to our oncall channel on failed builds on main branch
- had to do some weird stuff to make it work in such a way that we get notified while forked & dependabot PRs continue to build
- `context: Slack` is the thing that has the token to send a Slack notifications
- forked PRs (and dependabots) don't get access to secret contexts because security 🔒 which means that those builds would just fail to start as "Unauthorized"
- I wish we could just have external builds ignore the context but that's not how Circle works 😢 
[example of a forked build](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-java/1411/workflows/758a2193-b914-48fd-9f75-0efa43cbf794) - no slack notification step and no secrets …
> maint: notify slack on failed builds

- README.md
- build.gradle
- examples/spring-agent-manual/src/main/java/io/honeycomb/examples/springbootagentmanual/HelloController.java
- sdk/build.gradle
- smoke-tests/smoke-agent-manual.bats
Updates the OpenTelemetry SDK and JavaAgent dependencies to latest. Includes replacing the relocated `opentelemetry-extension-annotations` package the instrumentation repo and removing the OTLP HTTP exporter package as it's no longer required.
- Update OTel SDK to v1.19.0
- Update OTel JavaAgent to v1.19.1
- Replace extension-annotation package with new instrumentation-annotations package
- Updates example to use new import statement for `WithSpan`
- Remove OTLP http exporter package as it's now part of the `opentelemetry-exporter-otlp` package
- Update smoke tests to use new annotations package name
> Update Otel SDK and JavaAgent to v1.19.0/v1.19.1

- .circleci/config.yml
- slack notify channel name changed
> ci: fix slack notify channel

- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- common/src/test/java/io/honeycomb/opentelemetry/DistroMetadataTest.java
- custom/src/main/java/io/honeycomb/opentelemetry/DistroMetadataResourceProvider.java
- custom/src/test/java/io/honeycomb/opentelemetry/DistroMetadataResourceProviderTest.java
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
- updates https://github.com/honeycombio/telemetry-team/issues/394
- but still need to pull the new attribute out on ingest
- we cannot tell if people are using the sdk or the agent from current metadata
- deprecating previous function because it's a public API in a module we publish. it's unlikely anyone is using this class besides us, but technically it would be a breaking change.
> maint: additional metadata to diff sdk from agent

- CHANGELOG.md
- RELEASING.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- release needful
- no longer need to update in-product docs since those are a link to latest release
> rel: 1.4.1

- .github/dependabot.yml
- new version requires min Java version 11
- we build for min Java version 8
> maint: ignore mockito 5.x.x upgrade

- build.gradle
- gradle/shadow.gradle
- sdk/build.gradle
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
- bump to latest upstream agent version which includes auto-instrumented [JMX metrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/jmx-metrics/javaagent#jmx-metric-insight)
- a few things moved around
> maint: bump otel to 1.22.1

- .gitignore
- RELEASING.md
- agent/build.gradle
- licenses/licenses.md
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/byte-buddy-dep-1.12.20.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/byte-buddy-dep-1.12.20.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/jackson-core-2.14.1.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/jackson-core-2.14.1.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/jackson-jr-objects-2.14.1.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/jackson-jr-objects-2.14.1.jar/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/okhttp-4.10.0.jar/okhttp3/internal/publicsuffix/NOTICE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/zipkin-2.23.2.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/zipkin-reporter-2.16.3.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.22.1.jar/META-INF/licenses/zipkin-sender-okhttp3-2.16.3.jar/META-INF/LICENSE
- licenses/opentelemetry-javaagent-1.22.1.jar/inst/META-INF/LICENSE.renamed
- licenses/opentelemetry-javaagent-1.22.1.jar/inst/META-INF/NOTICE
- licenses/opentelemetry-javaagent-1.22.1.jar/inst/okhttp3/internal/publicsuffix/NOTICE
It is a legal requirement to include the license of any software used to build distributable artifacts. This PR adds the [Gradle-License-Report](https://github.com/jk1/Gradle-License-Report) plugin to the agent's Gradle file so that we have a job to run to generate license files for dependencies. This is also how [upstream Opentelemetry Java handles dependency licenses](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/dc2c4f630a95a4fc8f04d39a374ac297736c99b9/javaagent/build.gradle.kts#L6).
It also updates the releasing.md to include the steps to ensure this is updated as part of the release process.
- Updates the agent's gradle file to include the license plugin
- Adds all licenses and a license report under the `/licenses` directory
- Updates the release notes to …
> maint: Add dependency license files

- README.md
CI status badge does not render on the README
We must've revoked the api token in circle at some point, so badge stopped showing up on the readme. We shouldn't need the api token anyway, because it's a public repo.
To verify, check this link: https://circleci.com/gh/honeycombio/honeycomb-opentelemetry-java.svg?style=shield
> docs: fix ci status badge

- .circleci/config.yml
- smoke-tests/docker-compose.yml
- trying to run smoke tests locally using `openjdk:17-jdk-alpine` results in error `no matching manifest for linux/arm64/v8 in the manifest list entries`
- swap out [openjdk](https://hub.docker.com/_/openjdk) for [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin). I could just use a non-alpine image, but it also shows this is a deprecated image (see [here](https://github.com/docker-library/openjdk/issues/505)) so figured I'd swap out now.
- updated the ubuntu machine image in circle to work with the new jdk image
- updated collector version to 0.69. The file exporter changed in v0.70.0 and will need a few other changes to work for us, but this is at least newer than the version we were using.
> maint: update docker image and collector version in smoke tests

- CHANGELOG.md
- README.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
Prepares the v1.5.1 release.
- Adds changelog entry
- Updates version to 1.5.1, next snapshot to 1.5.2
- Update README with new upstream OTel versions
> rel: Prepeare v1.5.1 release

- CHANGELOG.md
- README.md
- RELEASING.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
- release prep for v1.5.2
- update releasing doc for how to find proto version in otel java, and how to update in tests
- update version in root build.gradle to 1.5.2
- update otel version to 1.27.0 and proto version to 0.20.0 in distrometadata
- update changelog for v1.5.2
- update readme with otel versions 1.27.0
- update test with new proto version
A docs PR has been prepped with the new release version, to be merged once this release is out.
> rel: prep release v1.5.2

- .circleci/config.yml
- common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java
- common/src/test/java/io/honeycomb/opentelemetry/EnvironmentConfigurationTest.java
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
We've released Ingest Keys, but need to update the key detection logic to allow Ingest Keys to be used to send data to Classic environments.
- updates the Legacy (Classic) API Key detection logic to understand the shape of a Classic Ingest Key
- Adds a new parameterized test with more detailed test cases
- Renames `isLegacyKey` with `isClassicKey`
- bonus: updated the circleCI image for smoke tests to `ubuntu-2204:2024.01.1` since the one we were using [is deprecated](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177)
It should be possible to use [an ingest key](https://docs.honeycomb.io/working-with-your-data/settings/api-keys/#ingest-keys-1) pointed to a classic environment after this change. Please note that the ability to create ingest keys in classic …
> feat: add support for classic ingest keys

- CHANGELOG.md
- build.gradle
- common/src/main/java/io/honeycomb/opentelemetry/DistroMetadata.java
- licenses/licenses.md
- release prep for v1.6.0
- update version in root build.gradle to 1.6.0
- update changelog for v1.6.0
A [docs PR](https://github.com/honeycombio/docs/pull/2094) has been prepped with the new release version, to be merged once this release is out / docs is unfrozen.
> rel: prep release v1.6.0

- examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/Application.java
- examples/spring-sdk/src/main/java/io/honeycomb/examples/springbootsdk/HelloController.java
- sdk/src/main/java/io/honeycomb/opentelemetry/OpenTelemetryConfiguration.java
A nice-to-have that I've wanted from working with this SDK on personal projects.
Otel, for very very good reason, periodically batches telemetry before sending it upstream. When I'm writing short-lived command line apps, I need to `.shutdown()` the otel sdk before exiting the process.
But `shutdown` is only a method on the `OpenTelemetrySdk`, not `OpenTelemetry`, so I have to (gasp) cast it to the right type because I looked at the source code and could see that we return one of those. 
I don't know enough Java to know if this is a big no-no, but as a user this would be appreciated ❤️
> feat: return an OpenTelemetrySdk from the builder

- build.gradle
- sdk/src/test/java/io/honeycomb/opentelemetry/OpenTelemetryConfigurationTest.java
- outdated otel dependencies
- bump opentelemetry to [1.35](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.35.0)
- bump opentelemetry agent to [1.33.1](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.33.1)
- update test for new spanExporter name (upstream dropped fqdn in changes to exporter that makes it easier to debug configuration)
> maint: bump otel to 1.35/1.33.1
